function [train_clsnames, test_clsnames] = officialStringifyClasses(param_train, param_test)

clsnames = {'antelope', 'grizzly+bear', 'killer+whale', 'beaver', 'dalmatian', ...
            'persian+cat', 'horse', 'german+shepherd', 'blue+whale', 'siamese+cat', ...
            'skunk', 'mole', 'tiger', 'hippopotamus', 'leopard', 'moose', ...
            'spider+monkey', 'humpback+whale', 'elephant', 'gorilla', 'ox', ...
            'fox', 'sheep', 'seal', 'chimpanzee', 'hamster', ...
            'squirrel', 'rhinoceros', 'rabbit', 'bat', 'giraffe', ...
            'wolf', 'chihuahua', 'rat', 'weasel', 'otter', ...
            'buffalo', 'zebra', 'giant+panda', 'deer', 'bobcat', ...
            'pig', 'lion', 'mouse', 'polar+bear', 'collie',  ...
            'walrus', 'raccoon', 'cow', 'dolphin'};


train_clsnames = clsnames(param_train.train_classes);
test_clsnames = clsnames(param_test.test_classes);